### ISSUE TITLE
Error Token is invalid

### ISSUE THREAD

**Issue by petike05** [dfrnoch/discord-sniper#40]
I just try to run but i get this message:

```
Error Token is invalid
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022E1CA81B80>
Traceback (most recent call last):
  File "C:\Users\Péter\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Péter\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Péter\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\Péter\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Press any key to continue . . .
```

What is the problem?

**Comment by BunnyFunner** [comment]
Token is invalid

**Comment by godkama** [comment]
> Token is invalid

Had the same error and trying to change with another token doesn't work
